server:
  port: 9999

magic-api:
  web: /magic/web # UI请求的界面以及UI服务地址
  resource: #配置存储方式
    type: database # 配置存储在数据库中资源存储类型，默认为存文件，可选file、database、redis
    table-name: magic_api_file # 数据库中的表名，此项为database专用
    # location: /data/magic-api # 配置文件存储位置。当以classpath开头时，为只读模式, 且可以读jar内资源, 此项配置为file专用
    datasource: null #指定数据源（单数据源时无需配置，多数据源时默认使用主数据源，如果存在其他数据源中需要指定。）
    prefix: magic-api-starter # 使用database、redis存储时的key前缀
    readonly: false # 是否是只读模式
  prefix: / # 接口前缀，可以不配置
  auto-import-module: db  # 自动导入的模块
  auto-import-package: java.lang.*,java.util.* #自动导包
  allow-override: false #禁止覆盖应用接口
  sql-column-case: camel #启用驼峰命名转换
  editor-config: classpath:./magic-editor-config.js #编辑器配置
  support-cross-domain: true # 跨域支持，默认开启
  secret-key: 123456789 # 远程推送时的秘钥，未配置则不开启推送
  push-path: /_magic-api-sync #远程推送的路径，默认为/_magic-api-sync
  show-sql: true #配置打印SQL
  compile-cache-size: 500 #配置编译缓存容量
  persistence-response-body: true #是否持久化保存ResponseBody
  date-pattern: # 配置请求参数支持的日期格式
    - yyyy-MM-dd
    - yyyy-MM-dd HH:mm:ss
    - yyyyMMddHHmmss
    - yyyyMMdd
  response: |- #配置JSON格式，格式为magic-script中的表达式
    {
      code: code,
      message: message,
      data,
      timestamp,
      requestTime,
      executeTime,
    }
  cluster-config:
    enable: false # 是否开启集群配置
  response-code-config:
    success: 200 #执行成功的code值
    invalid: 400 #参数验证未通过的code值
    exception: 500 #执行出现异常的code值
  banner: true # 打印banner
  thread-pool-executor-size: 8 # async语句的线程池大小
  throw-exception: false #执行出错时是否抛出异常
  backup-config: #备份相关配置
    max-history: -1 #备份保留天数，-1为永久保留
    # location: /data/magic-api/backup # 备份存储位置
    resource-type: database #备份存储方式，默认为文件，可选 database
    datasource: null  #指定数据源（单数据源时无需配置，多数据源时默认使用主数据源，如果存在其他数据源中需要指定。）
    table-name: magic_api_backup #使用数据库存储备份时的表名，此项为database专用
  crud-config: # CRUD相关配置
    logic-delete-column: deleted #逻辑删除列
    logic-delete-value: 1 #逻辑删除值
  cache-config: # 缓存相关配置
    capacity: 10000 #缓存容量
    ttl: -1 # 永不过期
    enable: true # 启用缓存
  page-config:
    size: size # 页大小的参数名称
    page: page # 页码的参数名称
    default-page: 1 # 未传页码时的默认首页
    default-size: 10 # 未传页大小时的默认页大小
  security-config:  # 安全配置
    username: admin # 登录用的用户名
    password: admin # 登录用的密码
  swagger-config:
    version: 1.0
    description: MagicAPI 接口信息
    title: MagicAPI Swagger Docs
    name: MagicAPI 接口
    location: /v2/api-docs/magic-api/swagger2.json
  debug-config:
    timeout: 60 # 断点超时时间，默认60s

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/magic-api-starter?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
